"""empty message

Revision ID: 6d029384b8a7
Revises: 77b286610d6b
Create Date: 2025-10-26 15:06:05.432153

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6d029384b8a7'
down_revision = '77b286610d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usereventsattendeeslink',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.drop_table('usereventsattendieslink')
    op.add_column('personuserfollowerslink', sa.Column('notify', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personuserfollowerslink', 'notify')
    op.create_table('usereventsattendieslink',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('usereventsattendieslink_event_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('usereventsattendieslink_user_id_fkey')),
    sa.PrimaryKeyConstraint('event_id', 'user_id', name=op.f('usereventsattendieslink_pkey'))
    )
    op.drop_table('usereventsattendeeslink')
    # ### end Alembic commands ###
