"""empty message

Revision ID: 7599ff9010be
Revises: 97d630beca1e
Create Date: 2025-10-25 16:51:33.983478

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7599ff9010be'
down_revision = '97d630beca1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('last_modified', sa.DateTime(), nullable=False))
    op.add_column('person', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('person', sa.Column('last_modified', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('last_modified', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_modified')
    op.drop_column('user', 'created_date')
    op.drop_column('person', 'last_modified')
    op.drop_column('person', 'created_date')
    op.drop_column('event', 'last_modified')
    op.drop_column('event', 'created_date')
    # ### end Alembic commands ###
