"""empty message

Revision ID: 77b286610d6b
Revises: 7599ff9010be
Create Date: 2025-10-25 17:02:18.358432

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '77b286610d6b'
down_revision = '7599ff9010be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
