"""empty message

Revision ID: 97d630beca1e
Revises: b8295569617e
Create Date: 2025-10-25 10:48:41.592196

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '97d630beca1e'
down_revision = 'b8295569617e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inviteation',
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('expire_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inviteation')
    # ### end Alembic commands ###
